### PR TITLE
update symfony console

### PR DESCRIPTION
**Pull request by Nemo64**
I noticed that the symfony/console dependency is outdated and there seems to be no reason not to use the newer one.

### CODE REVIEW

**Comment by Nemo64** [comment]
The travis test seems to be defective. The lock file will be ignored if this library is installed by someone. Then the older dependencies should kick in.

**Comment by mpdude** [comment]
Thanks for your suggestion, and thanks for your first PR on this repo!

I've removed the `composer.lock` file via #49. You could try to rebase this PR branch on `master`, that might make the Travis failure go away?

**Comment by Nemo64** [comment]
@mpdude done, and worked

**Comment by mpdude** [comment]
Danke @Nemo64!

**Pull request merged**
