### PR TITLE
Data containing backslashes is not properly escaped, possibly only when using the "masked" dump type

### PR DESCRIPTION
**Pull request by dominikkukacka**
fixes the '/' problem in the data export

### CODE REVIEW

**Comment by mpdude** [comment]
Thanks for opening a pull request!

Could you explain what exactly this tries to solve?

Also – whatever the issue is – I am not sure if `addslashes` is the right approach here. From [the docs](http://php.net/manual/en/function.addslashes.php):

> The addslashes() is sometimes incorrectly used to try to prevent SQL Injection. Instead, database-specific escaping functions and/or prepared statements should be used.

**Comment by dominikkukacka** [comment]
I had slashes in my database which resultet in invalid SQL Statements
beeing generated. like: '/'

I am also not sure if this is the right aproach.

Matthias Pigulla <notifications@github.com> schrieb am Mo., 6. Aug. 2018,
22:43:

**Comment by mpdude** [comment]
That looks like valid SQL, doesn’t it?

Can you provide the complete statement and the resulting error message?

**Comment by dominikkukacka** [comment]
Ah I missremembered the error. Sorry.
This is the exact one:
`2018-08-07T09:58:07.277176800Z ERROR at line 113277: Unknown command '\''.`

And here the corresponding lines:

```
INSERT INTO `accounts` (..., `name`, ...) VALUES 
...
(..., 'O\'Reillyberg', ...),
...
```

**Comment by dominikkukacka** [comment]
I found another problem:
The original value in a column is: `g\`
I export it via `dump="mask"` 
Which will result in: `'x\'`
Which is invalid of course.

So actually the addslashes will not work as the problem is the backslash.

**Comment by mpdude** [comment]
Could you please try to prepare some SQL statements to setup a database and a corresponding config file that we could use to reproduce this problem?

**Comment by dominikkukacka** [comment]
Here are the files I used to replicate it:
https://gist.github.com/dominikkukacka/817915ff48a83066043f75417f2213c9

The slimdump export:
`/root/.composer/vendor/bin/slimdump --buffer-size=512MB mysql://root:password@mysql:3306/test test.xml > dump.sql`

The resulting SQL dump:
```
INSERT INTO `test` (`id`, `name`) VALUES 
('1', 'O\'Reillyberg');
```

**Comment by mpdude** [comment]
The resulting file (`dump.sql`) was the same for me. I could import it without problems.

**Comment by dominikkukacka** [comment]
Mhm now I can't reproduce it anymore. Everything is escaped as it should be.

**Pull request closed without merging**
